manifest:
  remotes:
    - name: dnlbauer
      url-base: https://github.com/dnlbauer
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-corax
      remote: dnlbauer
      revision: main
  self:
    path: config
